

DROP TABLE PROCEEDING;
DROP TABLE PROJECT;
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;



CREATE TABLE DEPARTMENT (
     DEPT_NO        VARCHAR2(15 BYTE) NOT NULL,
     DEPT_NAME      VARCHAR2(30 BYTE),
     DEPT_LOCATION  VARCHAR2(50 BYTE),
     CONSTRAINT PK_DNO PRIMARY KEY(DEPT_NO)
);

CREATE TABLE EMPLOYEE (
    EMP_NO NUMBER NOT NULL,
    DEPT_NO VARCHAR2(15 BYTE),
    POSITION CHAR(10 BYTE),
    NAME VARCHAR2(15 BYTE),
    HIRE_DATE DATE,
    SALARY NUMBER,
    CONSTRAINT PK_ENO PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMP_DEP FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO) ON DELETE SET NULL -- 부서가 없어지면 사원의 부서 정보만 NULL처리 된다.
);
    
CREATE TABLE PROJECT (
    PJT_NO NUMBER NOT NULL,
    PJT_NAME VARCHAR2(30 BYTE),
    BEGIN_DATE DATE,
    END_DATE DATE,
    CONSTRAINT PK_PJNO PRIMARY KEY(PJT_NO)
);

CREATE TABLE PROCEEDING (
    PCD_NO NUMBER NOT NULL,
    EMP_NO NUMBER,
    PJT_NO NUMBER,
    PJT_STATE NUMBER NOT NULL,
    CONSTRAINT PK_PCDNO PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PROC_EMP FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO) ON DELETE SET NULL, 
    CONSTRAINT FK_PROC_PRO FOREIGN KEY(PJT_NO) REFERENCES PROJECT(PJT_NO) ON DELETE SET NULL
);
