/*
    DDL
    1. DaTa Definition Language
    2. 데이터 정의어
    3. 데이터베이스 객체(USER, TABLE, SEQUENCE, VIEW, INDEX 등)를 생성/수정/삭제하는 언어이다.
    4. 완료된 작업을 취소할 수 없다.(COMMIT 할 필요가 없다. ROLLBACK을 할 수 없다.)
    5. 종류
        1) CREATE : 생성
        2) ALTER  : 수정
        3) DROP   : 삭제
*/


DROP TABLE CUSTOMER_TBL;
DROP TABLE BANK_TBL;


CREATE TABLE BANK_TBL (
   BANK_CODE VARCHAR2(20 BYTE),
   BANK_NAME VARCHAR2(30 BYTE),
   CONSTRAINT PK_BANK PRIMARY KEY(BANK_CODE)
);

CREATE TABLE CUSTOMER_TBL (
          NO NUMBER,
        NAME VARCHAR2(30 BYTE) NOT NULL,
       PHONE VARCHAR2(30 BYTE) UNIQUE,
         AGE NUMBER(3)         CHECK(AGE BETWEEN 0 AND 100),
   BANK_CODE VARCHAR2(20 BYTE),
   CONSTRAINT PK_CUSTOMER PRIMARY KEY(NO),
   CONSTRAINT FK_CUSTOMER_BANK FOREIGN KEY(BANK_CODE) REFERENCES BANK_TBL(BANK_CODE)
);

