-- 테이블의 구조파악
DESC EMPLOYEES;  -- DESCRIBE

-- 1. EMPLOYEES 테이블에서 FIRST_NAME, LAST_NAME 조회하기
SELECT FIRST_NAME, LAST_NAME      -- FIRST_NAME 의 별명 AS > FNAME 칼럼만 가능
  FROM EMPLOYEES;        -- HR계정에 EMPLOYEES 테이블 ( EMPLOYEES 테이블의 오너를 명시 ) "E" < 별명을 주며 간단하게 실행

-- 2. EMPLOYEES 테이블에서 DEPARTMENT_ID를 중복 제거하고 조회하기
SELECT DISTINCT DEPARTMENT_ID   -- "DISTINCT" 중복 제거
  FROM EMPLOYEES;  

-- 3. EMPLOYEES 테이블에서 EMPLOYEES_ID가 150인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 WHERE EMPLOYEE_ID = 150;  -- WHERE절(조건)의 등호(=)는 비교 연산자이다.

-- 4. EMPLOYEES 테이블에서 SALARY가 10000 ~ 20000 사이인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE SALARY BETWEEN 10000 AND 20000;

-- 5. EMPLOYEES 테이블에서 DEPARTMENT_ID가 30, 40, 50인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN(30, 40, 50);
 
-- 6. EMPLOYEES 테이블에서 DEPARTMENT_ID가 NULL인 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IS NULL;   -- IS NOT NULL
 
 
 -- 7. EMPLOYEES 테이블에서 PHONE_NUMBER가 515로 시작하는 사원 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER
  FROM EMPLOYEES
 WHERE PHONE_NUMBER LIKE '515%';  -- 와일트카드( % )를 사용시 LIKE로 해줘야 와일드카드를 인식함 "="로 한다면 515%를 찾음
-- PHONE_NUMBER NOT LIKE '515%'; 할시 515로 시작되지 않는 값들을 출력
-- '515_'  < 515뒤에 한 글자만 더 들어올 수 있다. 


-- 8. EMPLOYEES 테이블을 FIRST_NAME의 가나다순(오름차순 : Ascending Sort)으로 정렬해서 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 ORDER BY FIRST_NAME ASC;  -- ASC는 생략 가능하다. 명시 안 해줘도 오름차순으로 출력 됨
 
 -- 9. EMPLOYEES 테이블을 높은 SALARY(내림차순 : Descnding Sort)를 받는 사원을 먼저 조회하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 ORDER BY SALARY DESC;  -- DESC는 생략이 불가능하다.

-- 10. EMPLOYEES 테이블의 사원들을 DEPARTMENT_ID 순으로 조회하고, 동일한 DEPARTMENT_ID를 가진 사원들은 높은 SALARY순으로 조히하기
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT_ID, SALARY
  FROM EMPLOYEES
 ORDER BY DEPARTMENT_ID ASC, SALARY DESC;
























